### ISSUE TITLE
Do not see latest changes on server

### ISSUE THREAD

**Issue by thisisclement** [thisisclement/Foundation6#12]
Hey @jaspersorrio , 

I'm seeing this in my localhost:
![screen shot 2016-05-18 at 1 36 48 am](https://cloud.githubusercontent.com/assets/7748640/15332665/1e59fc98-1c99-11e6-81c0-d0789b15b5f8.png)

But on http://theapprenticeshipcollective.com/ i dont see the latest copy.

Steps that I did:
- Did my local changes
- Push to github
- Pull from github on server
- Verified that i see the same on my localhost as well as server version

Hmmm not sure what went wrong here? Can help take a look? Thanks!

**Comment by jaspersorrio** [comment]
Yes about that! I actually moved TAC to my server because I realised that we actually set the first site up on the mail server .

Why can't we set it to be hosted on the mail server? Because the mail server will remove some site hosting dependencies due to clashing of ports etc. so the bottom line is it cannot be hosted with the mail server so I took it out and into my server. 

When I have more time and when the email is functioning, I will create an account for you in my server so you can ssh in to make changes. In the meantime, let me know whenever you want to update TAC site.

Sorry I didn't tell you yesterday! I intended to ,but I guess I was exhausted.. Had a super long day yesterday 😭😭

**Comment by thisisclement** [comment]
@jaspersorrio: Ah no wonder! hahaha. I thought what happened!! It's okay, at least now we know heh. Thanks for hosting it on your server first!  👍 Lemme know if it affects any of your current space/load on your server k.
I will continue to make changes then let you know when to pull the git on your server. :)

Btw I'm gonna buy hellotac.org now.. theapprenticeshipcollective.com very hard to type as a web address. lol. Not sure if you've already made the settings to reference the domain name yet?

**Comment by jaspersorrio** [comment]
@thisisclement Alright! great!! Can you please change the nameservers to ns1.digitalocean.com, ns2.digitalocean.com, ns3.digitalocean.com.

**Comment by thisisclement** [comment]
@jaspersorrio : It is to be added under personal DNS server?
![screen shot 2016-05-19 at 11 28 49 pm](https://cloud.githubusercontent.com/assets/7748640/15399272/90ec33b2-1e19-11e6-88e0-924c52882b9e.png)

**Comment by thisisclement** [comment]
Ah ok , i think you have updated it, just saw it, thanks!
