### ISSUE TITLE
Faulty Carousel

### ISSUE THREAD

**Issue by jaspersorrio** [thisisclement/Foundation6#13]
Carousel only has 3 dots.
Expected 1 dot for every thumbnail.
<img width="1221" alt="screen shot 2016-05-19 at 11 14 55 am" src="https://cloud.githubusercontent.com/assets/10573718/15381548/f3d9a016-1db2-11e6-815e-f73ed6cd4261.png">

When scrolling right, dots do not "change position" until accounts manager is in the middle.

**Comment by thisisclement** [comment]
Hey jasper, there are total 7 thumbnails for each apprenticeship. I've only configured to show 3 at a time, so there will be 3 per page. That's why you have 3 pages and each dot represents one page. 

If you see mobile, it is configured to show 1 thumbnail at a time (1 per page) hence seeing 7 dots in total. Hope this clarifies!
